### ISSUE TITLE
[Fix] Nav 디자인 수정 제안

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web-v2#5]
## 📔 Description

Nav의 height가 실물로 보니 너무 넓고
*** 고객님 안녕하세요 부분이 오른쪽의 약간을 마진을 가지고 있어 페이지들의 요소가 중간에 있는 것처럼 느껴지지가 않음

<img width="1920" alt="스크린샷 2023-09-20 오후 11 07 37" src="https://github.com/YU-RentCar/yurentcar-fe-web-v2/assets/54520200/64fc1dfd-09bb-4cdd-801b-248f27c54657">

- 보다시피 페이지 요소가 약간 오른쪽으로 치우쳐 있는 느낌이 있음.
- height가 너무 큼

<img width="1920" alt="스크린샷 2023-09-20 오후 11 07 55" src="https://github.com/YU-RentCar/yurentcar-fe-web-v2/assets/54520200/67565b7a-3f5a-436f-a0e7-38d1dedafa07">

- *** 고객님 안녕하세요 부분의 오른쪽 마진을 없엠
- height를 줄임

<br>

이런 식으로 오른쪽 마진을 없에고 height를 약간 줄이는 방식으로 fix 하고자 함.
댓글로 의견을 말해주면 이후 브랜치 생성

<br>

## 🐈 Todo

- [x] *** 고객님 안녕하세요 부분의 오른쪽 마진을 없엠
- [x] height 줄임
- [x] 로고 크기 줄임

<br>

**Comment by yh-project** [comment]
멘트의 우측 마진을 없애는 것과 Nav 의 height 을 줄이는 것은 동의하나 로고의 크기는 줄이면 더 이상 로고가 제대로 보이지 않을 것 같아서 로고의 역할을 잃을 것 같아서 그대로 뒀으면 하네요

**Comment by seolbotdae** [comment]
아 밑의 사진에서 로고도 같이 줄인건데 적지를 않았네요. 저정도 크기인데 어떻게 할까요
